config/routes.rb
Rails.application.routes.draw do
  
  root 'posts#index'
  
  resources :posts
  post 'posts/:id/comments/create' => 'comments#create'
  delete 'comments/:id' => 'comments#destroy'
  
  # cafe
  resources :cafes, except: [:destroy]
  
  # authenticate
  get '/sign_up' => 'authenticate#sign_up'
  post '/sign_up' => 'authenticate#user_sign_up'
  get '/sign_in' => 'authenticate#sign_in'
  post '/sign_in' => 'authenticate#user_sign_in'
  delete '/sign_out' => 'authenticate#sign_out'
  get '/user_info/:user_name' => 'authenticate#user_info'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
  
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :post
end

app/models/daum.rb
class Daum < ApplicationRecord
    has_many :memberships
    has_many :users, through: :memberships
end

app/models/membership.rb
class Membership < ApplicationRecord
    belongs_to :user
    belongs_to :daum
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :memberships
    has_many :daums, through: :memberships
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :user_signed_in?, :current_user
  
  def user_signed_in?
      session[:sign_in_user].present?
  end
  
  def authenticate_user!
      redirect_to sign_in_path unless user_signed_in?
  end
  
  def current_user
      @current_user = User.find(session[:sign_in_user]) if user_signed_in?
      
  end
end

app/controllers/authenticate_controller.rb
class AuthenticateController < ApplicationController
    # 회원가입 페이지
    def sign_up
    end
    # 실제 회원가입 로직
    def user_sign_up
        @user = User.new(user_name: params[:user_name],
                         password: params[:password],
                         password_confirmation: params[:confirmation])
        if @user.save
            redirect_to root_path, flash: {success: '회원가입 성공'}
        else
            redirect_to :back, flash: {success: '회원가입 실패'}
        end
    end
    # 로그인 페이지
    def sign_in
    end
    # 실제 로그인 로직
    def user_sign_in
        @user = User.find_by(user_name: params[:user_name])
        if @user.present? and @user.authenticate(params[:password])
            session[:sign_in_user] = @user.id
            redirect_to root_path, flash: {success: '로그인 성공'}
        else
            redirect_to :back, flash: {danger: '로그인 정보를 확인하세요'}
        end
    end
    # 유저 정보 페이지
    # 로그아웃 로직
    def sign_out
        session.delete(:sign_in_user)
        redirect_to :back, flash: {warning: '로그아웃됨'}
    end
end

app/controllers/cafes_controller.rb
class CafesController < ApplicationController
    # 전체 카페 목록보여주는 페이지
    # -> 로그인 하지 않았을 때: 전체 카페 목록
    # -> 로그인 했을때: 유저가 가입한 카페 목록
    def index
        if user_signed_in?
            @cafes = current_user.daums
        else
            @cafes = Daum.all
        end
    end
    
    # 카페 내용물을 보여주는 페이지(이 카페의 게시물)
    def show
        @cafe = Daum.find(params[:id])
    end
    
    # 카페를 개설하는 페이지
    def new
        @cafe = Daum.new
    end
    # 카페를 실제로 개설하는 로직
    def create
        @cafe = Daum.new(daum_params)
        @cafe.master_name = current_user.user_name
        if @cafe.save
            redirect_to cafe_path(@cafe), flash: {success: "카페가 개설되었습니다."}
        else
            redirect_to :back, flash: {danger: "카페 개설에 실패했습니다."}
        end
    end
    # 카페 정보 수정하는 페이지
    # 카페 정보를 실제로 수정하는 로직
    
    private
    def daum_params
        params.require(:daum).permit(:title, :description)
        # :params => {:daum => {:title => "...", :description => "..."}}
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.new
    comment.content = params[:content]
    comment.post_id = params[:id]
    comment.save
    
    redirect_to :back
  end

  def destroy
    comment = Comment.find(params[:id])
    comment.destroy
    
    redirect_to :back
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post, flash: {success: 'Post was successfully created.'}
    else
      render :new
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    if @post.update(post_params)
      redirect_to @post, flash: {success: 'Post was successfully updated.'}
    else
      render :edit
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    redirect_to posts_url, flash: {success: 'Post was successfully destroyed.'}
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :contents)
      # {title: params[:post][:title], contents: [:post][:contents]}
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authenticate_helper.rb
module AuthenticateHelper
end

app/helpers/cafes_helper.rb
module CafesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/authenticate/sign_in.html.erb
<h1>로그인</h1>
<%= form_tag do %>
    <%= text_field_tag :user_name %><br/>
    <%= password_field_tag :password %><br/>
    <%= submit_tag 'Sign In' %>
<% end %>

app/views/authenticate/sign_up.html.erb
<h1>회원가입</h1>
<%= form_tag do %>
    <%= text_field_tag :user_name %><br/>
    <%= password_field_tag :password %><br/>
    <%= password_field_tag :password_confirmation %><br/>
    <%= submit_tag 'Sign Up' %>
<% end %>

app/views/cafes/new.html.erb
<h1>카페 개설하기</h1>
<%= form_for(@cafe, url: cafes_path) do |f| %>
    <%= f.text_field :title %><br/>
    <%= f.text_area :description %><br/>
    <%= f.submit 'Create Cafe' %>
<% end %>

app/views/comments/_form.html.erb
<%= form_tag("/posts/#{post.id}/comments/create") do %>
    <!--# 댓글 입력폼-->
    <%= text_field_tag(:content, nil, class: "form-control", placeholder: "내용을 입력하세요") %>
    <br>
    <!--# 전송버튼-->
    <%= submit_tag("댓글작성", class: "btn btn-primary")%>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DaumCafe</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/nav' %>
    <% flash.each do |k, v| %>
      <div class="alert alert-<%= k %>"><%= v %></div>
    <% end %>
    <div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for(post, html: {class: 'text-center'}) do |f| %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :contents %>
    <%= f.text_area :contents, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit '작성하기', class: 'btn btn-info' %>
    <%= link_to '뒤로가기', posts_path, class: 'btn btn-warning text-white' %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

app/views/posts/index.html.erb
<h1>Posts</h1>

<ul class="list-group">
  <% @posts.each do |post| %>
  <li class="list-group-item d-flex justify-content-between align-items-center">
    <%= link_to "#{post.title}", post_path(post) %>
    <span class="badge badge-primary badge-pill"><%= post.comments.count %></span>
  </li>
  <% end %>
</ul>
<div class="text-center">
<%= link_to 'New Post', new_post_path, class: 'btn btn-info' %>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<h1>
  <strong>Title:</strong>
  <%= @post.title %>
</h1>
<hr/>

<p>
  <strong>Contents:</strong>
  <%= @post.contents %>
</p>

<%= link_to '수정', edit_post_path(@post), class: 'btn btn-warning text-white' %> |
<%= link_to '목록', posts_path, class: 'btn btn-info' %>|
<%= link_to '삭제', post_path(@post), class: 'btn btn-danger', method: 'DELETE', data: {confirm: "삭제하시겠습니까?"} %>

<hr>
<!--# 댓글 입력-->
<%= render 'comments/form', post: @post %>

<br>
<!--# 댓글 리스트-->

<table class="table">
  <thead>
    <tr>
      <th scope="col">Id</th>
      <th scope="col">Content</th>
      <th scope="col">Button</th>
    </tr>
  </thead>
  
  <tbody>
  <% @post.comments.each do |comment| %>
    <tr>
      <th scope="row"><%= comment.id %>
      <td><%= comment.content %>
      <td><%= link_to "삭제", "/comments/#{comment.id}", 
      method: "delete" %><td>
    </tr>
  <% end %>
  </tbody>
</table>


  

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="container">
    <span class="text-muted">Place sticky footer content here.</span>
  </div>
</footer>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Never expand</a>
  <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarsExample01" aria-controls="navbarsExample01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="navbar-collapse collapse" id="navbarsExample01" style="">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <% unless user_signed_in? %>
      <li class="nav-item">
        <%= link_to 'Sign In', sign_in_path, class: 'nav-link' %>
      </li>
      <% else %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><%= current_user.user_name %></a>
        <div class="dropdown-menu" aria-labelledby="dropdown01">
          <%= link_to 'Sign Out', sign_out_path, method: 'delete', class: 'dropdown-item', data: {confirm: '로그아웃 하시겠습니까?'} %>
        </div>
      </li>
      <% end %>
    </ul>
    <form class="form-inline my-2 my-md-0">
      <input class="form-control" type="text" placeholder="Search" aria-label="Search">
    </form>
  </div>
</nav>